people:
  Alice:
    age: 37
    job: advanced bazification research
    pets:
      Ham Ham:
        species: hamster
        age: 2
        likes: carrots
        dislikes: sneks
  Jeremy:
    age: 23
    job: frobnicator
    pets:
      Spanky:
        species: dog
        age: 3
        likes: naps
        dislikes: sneks
      Mr. Waffles:
        species: cat
        age: 7
        likes: the flesh of the weak
        dislikes: sneks
  Bob:
    age: 40
    job: prognosticator

days:
- english: Monday
  french:  Lundi
  swedish: Måndag

- english: Tuesday
  french:  Mardi
  swedish: Tisdag

- english: Wednesday
  french:  Mercredi
  swedish: Onsdag

- english: Thursday
  french:  Jeudi
  swedish: Torsdag

- english: Friday
  french:  Vendredi
  swedish: Fredag

- english: Saturday
  french:  Samedi
  swedish: Lördag

- english: Sunday
  french:  Dimache
  swedish: Söndag
