#!/usr/bin/env python3

import jinja2, yaml

class Person:
  def __init__(self, name, *, age, job, pets=()):
    self.name      = name
    self.age       = int(age)
    self.job       = job
    self.pets      = [Pet(name, **pets[name]) for name in pets]

class Pet:
  def __init__(self, name, *, species, age, likes):
    self.name     = name
    self.age      = int(age)
    self.likes    = likes
    self.species  = species

class Day:
  def __init__(self, *, english, french, swedish):
    self.english = english
    self.french  = french
    self.swedish = swedish

class Context:
  def __init__(self, people, days):
    self.people = [Person(name, **people[name]) for name in people]
    self.days   = [Day(**day) for day in days]
  def __iter__(self):
    return self.__dict__.items().__iter__()

# load the config file
with open('config.yaml', 'r') as f:
  config = yaml.load(f.read())

context = Context(**config)

environment = jinja2.Environment(
  lstrip_blocks=True,
  trim_blocks=True,
  undefined=jinja2.StrictUndefined,
)

# load the template
with open('template.md', 'r') as f:
  template = environment.from_string(f.read())

output = template.render(context)

with open('output.md', 'w') as f:
  f.write(output)
